"""empty message

Revision ID: 888fb46d6f67
Revises: d37095a09400
Create Date: 2024-04-29 23:51:06.959701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888fb46d6f67'
down_revision: Union[str, None] = 'd37095a09400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jwt', sa.Column('user_agent', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jwt', 'user_agent')
    # ### end Alembic commands ###
