"""empty message

Revision ID: d37095a09400
Revises: eb9cc63b4de8
Create Date: 2024-04-29 04:53:30.859298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37095a09400'
down_revision: Union[str, None] = 'eb9cc63b4de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jwt', sa.Column('ip_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jwt', 'ip_address')
    # ### end Alembic commands ###
