version: "3.7"
services:
  db:
    image: postgres:16
    container_name: zoosalon_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5430:5432

  redis:
    image: redis:7
    container_name: zoosalon_redis
    depends_on:
      - db

  zoosalon:
    build:
      context: .
    container_name: zoosalon_app
    env_file:
      - .env

    command: ["/zoosalon/docker/app.sh"]
    ports:
      - 9000:8000
    depends_on:
      - db
      - redis
      - celery
  celery:
    build:
      context: .
    container_name: zoosalon_celery
    depends_on:
      - db
      - redis
    command: ["/zoosalon/docker/celery.sh",'celery']
    env_file:
      - .env

  beat:
    build:
      context: .
    container_name: zoosalon_beat
    depends_on:
      - db
      - redis
      - grafana

    command: [ "/zoosalon/docker/celery.sh",'beat' ]
    env_file:
      - .env

  flower:
    build:
      context: .
    container_name: zoosalon_flower
    depends_on:
      - db
      - redis
      - grafana

    command: [ "/zoosalon/docker/celery.sh",'flower' ]
    env_file:
      - .env
    ports:
      - 5555:5555
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
        - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
        - 3000:3000
volumes:
  postgresdata:
  grafanadata:
  prometheusdata: